import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Globe, ArrowRight, Radio } from 'lucide-react';
import SEO from '../components/SEO';
import Schema from '../components/Schema';
import { trackEvent } from '../utils/analytics';
import { getPage } from '../services/strapi';
import { StrapiPage } from '../types/strapi';
import Markdown from '../components/Markdown';

const STATIC_ABOUT_FALLBACK: StrapiPage = {
  id: 0,
  title: "About AeroSky Network",
  slug: "about",
  content: `## India's Airspace Intelligence Network

AeroSky is building **India's independent, community-powered airspace intelligence network**. By deploying a distributed grid of citizen-hosted receiver stations, we are creating a resilient, high-fidelity tracking infrastructure for Indian skies.

## Why it Matters

Traditional aviation tracking relies on centralized commercial receivers or foreign-hosted infrastructure. AeroSky decentralizes this by empowering aviation enthusiasts, developers, and professionals to host ground stations. This community-first approach ensures:

* **Unprecedented Local Coverage**: Capturing low-altitude and terrain-shielded flights that centralized grids miss.
* **Resilient Infrastructure**: A highly distributed, self-healing network that remains operational under any conditions.
* **Independent Airspace Data**: Ensuring that critical aviation intelligence is generated by the community, for the community, within India.

## Why Trust AeroSky?

* **Engineering-First Architecture**: Built on open-source protocols, modern hardware interfaces (RTL-SDR, Raspberry Pi), and high-frequency data pipelines.
* **Community-Owned Grid**: We do not claim to operate a pre-existing national tracking grid; instead, we are actively co-creating the network alongside our members.
* **Data Integrity**: Every data point is cryptographically verified from ground station to API, ensuring enterprise-grade credibility.

## How You Can Contribute

The network grows block by block, receiver by receiver. You can participate in two primary ways:

1. **Become an AeroCaptain (Host a Ground Station)**
   Host an ADS-B receiver kit on your rooftop or balcony. You will feed live airspace data directly to the network and receive exclusive founding member benefits, detailed coverage analytics, and network telemetry.
2. **Join as a Founding AeroCadet**
   Gain early access to our platform sandbox, contribute to our open-source tools, and help test our real-time airspace dashboards.`,
  seoTitle: "About Us | AeroSky — India's Airspace Intelligence Network",
  seoDescription: "AeroSky is India's community-powered airspace intelligence network. Learn about our mission to build independent aviation intelligence infrastructure.",
  publishedAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString()
};

const About: React.FC = () => {
  const [page, setPage] = useState<StrapiPage | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadPage() {
      try {
        const data = await getPage('about');
        if (data) {
          setPage(data);
        } else {
          setPage(STATIC_ABOUT_FALLBACK);
        }
      } catch (err) {
        console.error('Failed to load about page from CMS, using static fallback:', err);
        setPage(STATIC_ABOUT_FALLBACK);
      } finally {
        setLoading(false);
      }
    }
    loadPage();
  }, []);

  if (loading) {
    return (
      <div className="relative pt-24 pb-16 px-4 sm:px-6 md:px-12 lg:px-24 max-w-3xl mx-auto animate-pulse space-y-6">
        <div className="h-8 w-48 bg-white/5 rounded mx-auto" />
        <div className="h-64 bg-white/5 rounded-3xl animate-pulse" />
      </div>
    );
  }

  if (!page) {
    return (
      <div className="relative pt-24 pb-16 px-4 sm:px-6 md:px-12 lg:px-24 text-center">
        <SEO title="About Us | AeroSky" description="AeroSky airspace intelligence network" />
        <div className="text-sky-200/50 text-sm">About page is currently unavailable.</div>
      </div>
    );
  }

  return (
    <div className="relative pt-16">
      <SEO
        title={page.seoTitle || `${page.title} | AeroSky`}
        description={page.seoDescription || "AeroSky: India's independent airspace intelligence infrastructure."}
      />
      <Schema
        type="BreadcrumbList"
        data={{
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://aerosky.ai/' },
            { '@type': 'ListItem', position: 2, name: page.title, item: `https://aerosky.ai/${page.slug}` }
          ]
        }}
      />

      {/* Hero */}
      <section className="relative py-10 sm:py-14 px-4 sm:px-6 md:px-12 lg:px-24 text-center overflow-hidden">
        <div className="absolute inset-0">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-amber-500/[0.03] rounded-full blur-[120px]" />
        </div>
        <div className="relative z-10 max-w-4xl mx-auto animate-fade-in-up">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-saffron/30 bg-saffron/[0.08] text-saffron text-xs font-mono font-bold tracking-wider uppercase mb-6 animate-pulse-glow">
            <Globe size={14} /> About AeroSky
          </div>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight leading-[1] mb-3">
            <span className="text-white">{page.title}</span>
          </h1>
        </div>
      </section>

      {/* Content */}
      <section className="section-std !pt-4 pb-24">
        <div className="max-w-4xl mx-auto">
          <div className="glass rounded-2xl p-6 sm:p-8 border border-white/[0.05]">
            <Markdown content={page.content} />
            
            {/* Action buttons at the bottom of dynamic about content */}
            <div className="border-t border-white/5 pt-5 mt-5 flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/aerocaptains"
                onClick={() => trackEvent('hero_become_aerocaptain_clicked', { from: 'about_cta' })}
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-black font-bold text-sm transition-all hover:shadow-[0_0_20px_rgba(255,153,51,0.3)] hover:-translate-y-0.5 bg-gradient-to-br from-saffron to-gold"
              >
                <Radio size={16} /> Become an AeroCaptain
              </Link>
              <a
                href="/#pathways"
                onClick={() => trackEvent('newsletter_signup_started', { page: '/about', trigger: 'about_founding_cta' })}
                className="inline-flex items-center gap-2 px-6 py-3 rounded-xl border border-white/10 bg-white/[0.03] hover:bg-white/[0.06] text-white font-bold text-sm transition-all hover:-translate-y-0.5"
              >
                Join Founding Members <ArrowRight size={16} />
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default About;
